#!/bin/bash

ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/eru-agent"
SERVICE="$ROOT/usr/lib/systemd/system"

mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

mv agent $BIN/eru-agent
mv agent.yaml.sample $CONF
mv eru-agent.service $SERVICE

OUTPUT=($($BIN/eru-agent -v 2>&1))
VERSION=${OUTPUT[-1]%\"}
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-agent --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $CI_PROJECT_DIR --verbose --category 'Development/App' --description 'docker eru agent' --url 'http://github.com/projecteru/eru-agent' --license 'BSD'  --no-rpm-sign usr etc

rm -rf $ROOT
