#!/bin/bash

set -e
ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/eru"
SERVICE="$ROOT/usr/lib/systemd/system"
after_install_script="$ROOT/after_install.sh"

mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

cat > $after_install_script << EOF
systemctl daemon-reload
EOF

mv eru-agent $BIN/eru-agent
mv agent.yaml.sample $CONF
mv eru-agent.service $SERVICE

VERSION=$(cat VERSION)
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-agent --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --after-install $after_install_script --verbose --category 'Development/App' --description 'docker eru agent' --url 'https://github.com/projecteru2/agent' --license 'MIT'  --no-rpm-sign usr etc

rm -rf $ROOT
