// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	pb "github.com/projecteru2/core/rpc/gen"
	mock "github.com/stretchr/testify/mock"
)

// Detector is an autogenerated mock type for the Detector type
type Detector struct {
	mock.Mock
}

// Detect provides a mock function with given fields: _a0
func (_m *Detector) Detect(_a0 *pb.Node) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pb.Node) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
