// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/projecteru2/agent/source"
	"github.com/projecteru2/agent/types"
)

// NewSource creates a new instance of Source. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Source {
	mock := &Source{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Source is an autogenerated mock type for the Source type
type Source struct {
	mock.Mock
}

type Source_Expecter struct {
	mock *mock.Mock
}

func (_m *Source) EXPECT() *Source_Expecter {
	return &Source_Expecter{mock: &_m.Mock}
}

// Alive provides a mock function for the type Source
func (_mock *Source) Alive(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Alive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Source_Alive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alive'
type Source_Alive_Call struct {
	*mock.Call
}

// Alive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Source_Expecter) Alive(ctx any) *Source_Alive_Call {
	return &Source_Alive_Call{Call: _e.mock.On("Alive", ctx)}
}

func (_c *Source_Alive_Call) Run(run func(ctx context.Context)) *Source_Alive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Source_Alive_Call) Return(b bool) *Source_Alive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Source_Alive_Call) RunAndReturn(run func(ctx context.Context) bool) *Source_Alive_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function for the type Source
func (_mock *Source) Events(ctx context.Context) (<-chan *types.WorkloadEventMessage, <-chan error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan *types.WorkloadEventMessage
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan *types.WorkloadEventMessage, <-chan error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan *types.WorkloadEventMessage); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *types.WorkloadEventMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// Source_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type Source_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Source_Expecter) Events(ctx any) *Source_Events_Call {
	return &Source_Events_Call{Call: _e.mock.On("Events", ctx)}
}

func (_c *Source_Events_Call) Run(run func(ctx context.Context)) *Source_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Source_Events_Call) Return(workloadEventMessageCh <-chan *types.WorkloadEventMessage, errCh <-chan error) *Source_Events_Call {
	_c.Call.Return(workloadEventMessageCh, errCh)
	return _c
}

func (_c *Source_Events_Call) RunAndReturn(run func(ctx context.Context) (<-chan *types.WorkloadEventMessage, <-chan error)) *Source_Events_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Source
func (_mock *Source) Get(ctx context.Context, ID string) (*source.Workload, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *source.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*source.Workload, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *source.Workload); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*source.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Source_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Source_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *Source_Expecter) Get(ctx any, ID any) *Source_Get_Call {
	return &Source_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *Source_Get_Call) Run(run func(ctx context.Context, ID string)) *Source_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Source_Get_Call) Return(workload *source.Workload, err error) *Source_Get_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *Source_Get_Call) RunAndReturn(run func(ctx context.Context, ID string) (*source.Workload, error)) *Source_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Source
func (_mock *Source) List(ctx context.Context) ([]*source.Workload, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*source.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*source.Workload, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*source.Workload); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*source.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Source_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Source_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Source_Expecter) List(ctx any) *Source_List_Call {
	return &Source_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *Source_List_Call) Run(run func(ctx context.Context)) *Source_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Source_List_Call) Return(workloads []*source.Workload, err error) *Source_List_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *Source_List_Call) RunAndReturn(run func(ctx context.Context) ([]*source.Workload, error)) *Source_List_Call {
	_c.Call.Return(run)
	return _c
}
