// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	pb "github.com/projecteru2/core/rpc/gen"
	mock "github.com/stretchr/testify/mock"
)

// RPCClientPool is an autogenerated mock type for the RPCClientPool type
type RPCClientPool struct {
	mock.Mock
}

// GetClient provides a mock function with given fields:
func (_m *RPCClientPool) GetClient() pb.CoreRPCClient {
	ret := _m.Called()

	var r0 pb.CoreRPCClient
	if rf, ok := ret.Get(0).(func() pb.CoreRPCClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pb.CoreRPCClient)
		}
	}

	return r0
}
