// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/projecteru2/agent/types"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetIdentifier provides a mock function for the type Store
func (_mock *Store) GetIdentifier(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIdentifier")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Store_GetIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentifier'
type Store_GetIdentifier_Call struct {
	*mock.Call
}

// GetIdentifier is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) GetIdentifier(ctx any) *Store_GetIdentifier_Call {
	return &Store_GetIdentifier_Call{Call: _e.mock.On("GetIdentifier", ctx)}
}

func (_c *Store_GetIdentifier_Call) Run(run func(ctx context.Context)) *Store_GetIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_GetIdentifier_Call) Return(s string) *Store_GetIdentifier_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Store_GetIdentifier_Call) RunAndReturn(run func(ctx context.Context) string) *Store_GetIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetNode provides a mock function for the type Store
func (_mock *Store) GetNode(ctx context.Context, nodename string) (*types.Node, error) {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 *types.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Node, error)); ok {
		return returnFunc(ctx, nodename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Node); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type Store_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Store_Expecter) GetNode(ctx any, nodename any) *Store_GetNode_Call {
	return &Store_GetNode_Call{Call: _e.mock.On("GetNode", ctx, nodename)}
}

func (_c *Store_GetNode_Call) Run(run func(ctx context.Context, nodename string)) *Store_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_GetNode_Call) Return(node *types.Node, err error) *Store_GetNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *Store_GetNode_Call) RunAndReturn(run func(ctx context.Context, nodename string) (*types.Node, error)) *Store_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeStatus provides a mock function for the type Store
func (_mock *Store) GetNodeStatus(ctx context.Context, nodename string) (*types.NodeStatus, error) {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeStatus")
	}

	var r0 *types.NodeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.NodeStatus, error)); ok {
		return returnFunc(ctx, nodename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.NodeStatus); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NodeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_GetNodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeStatus'
type Store_GetNodeStatus_Call struct {
	*mock.Call
}

// GetNodeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Store_Expecter) GetNodeStatus(ctx any, nodename any) *Store_GetNodeStatus_Call {
	return &Store_GetNodeStatus_Call{Call: _e.mock.On("GetNodeStatus", ctx, nodename)}
}

func (_c *Store_GetNodeStatus_Call) Run(run func(ctx context.Context, nodename string)) *Store_GetNodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_GetNodeStatus_Call) Return(nodeStatus *types.NodeStatus, err error) *Store_GetNodeStatus_Call {
	_c.Call.Return(nodeStatus, err)
	return _c
}

func (_c *Store_GetNodeStatus_Call) RunAndReturn(run func(ctx context.Context, nodename string) (*types.NodeStatus, error)) *Store_GetNodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetNodeStatus provides a mock function for the type Store
func (_mock *Store) SetNodeStatus(ctx context.Context, ttl int64) error {
	ret := _mock.Called(ctx, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNodeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_SetNodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeStatus'
type Store_SetNodeStatus_Call struct {
	*mock.Call
}

// SetNodeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ttl int64
func (_e *Store_Expecter) SetNodeStatus(ctx any, ttl any) *Store_SetNodeStatus_Call {
	return &Store_SetNodeStatus_Call{Call: _e.mock.On("SetNodeStatus", ctx, ttl)}
}

func (_c *Store_SetNodeStatus_Call) Run(run func(ctx context.Context, ttl int64)) *Store_SetNodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_SetNodeStatus_Call) Return(err error) *Store_SetNodeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_SetNodeStatus_Call) RunAndReturn(run func(ctx context.Context, ttl int64) error) *Store_SetNodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetWorkloadStatus provides a mock function for the type Store
func (_mock *Store) SetWorkloadStatus(ctx context.Context, status *types.WorkloadStatus, ttl int64) error {
	ret := _mock.Called(ctx, status, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetWorkloadStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.WorkloadStatus, int64) error); ok {
		r0 = returnFunc(ctx, status, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_SetWorkloadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkloadStatus'
type Store_SetWorkloadStatus_Call struct {
	*mock.Call
}

// SetWorkloadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status *types.WorkloadStatus
//   - ttl int64
func (_e *Store_Expecter) SetWorkloadStatus(ctx any, status any, ttl any) *Store_SetWorkloadStatus_Call {
	return &Store_SetWorkloadStatus_Call{Call: _e.mock.On("SetWorkloadStatus", ctx, status, ttl)}
}

func (_c *Store_SetWorkloadStatus_Call) Run(run func(ctx context.Context, status *types.WorkloadStatus, ttl int64)) *Store_SetWorkloadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.WorkloadStatus
		if args[1] != nil {
			arg1 = args[1].(*types.WorkloadStatus)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Store_SetWorkloadStatus_Call) Return(err error) *Store_SetWorkloadStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_SetWorkloadStatus_Call) RunAndReturn(run func(ctx context.Context, status *types.WorkloadStatus, ttl int64) error) *Store_SetWorkloadStatus_Call {
	_c.Call.Return(run)
	return _c
}
