name: docker-image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ github.repository }}
          tags: |
            type=ref,event=tag

      - name: Docker meta for debug version
        if: ${{ github.ref == 'refs/heads/master' }}
        id: debug-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ github.repository }}
          tags: |
            type=sha,format=long,prefix=

      - name: Build and push image
        if: ${{ steps.meta.outputs.tags != '' }}
        uses: docker/build-push-action@v5
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: "[debug version] Build and push image"
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v5
        with:
          context: "."
          push: true
          build-args: |
            KEEP_SYMBOL=1
          tags: ${{ steps.debug-meta.outputs.tags }}
