name: test

on:
  push:
    tags:
      - '!v*'
    branches:
      - '*'
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: unit tests
        run: make test
