// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"

	"github.com/projecteru2/agent/types"
)

// NewRuntime creates a new instance of Runtime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runtime {
	mock := &Runtime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Runtime is an autogenerated mock type for the Runtime type
type Runtime struct {
	mock.Mock
}

type Runtime_Expecter struct {
	mock *mock.Mock
}

func (_m *Runtime) EXPECT() *Runtime_Expecter {
	return &Runtime_Expecter{mock: &_m.Mock}
}

// AttachWorkload provides a mock function for the type Runtime
func (_mock *Runtime) AttachWorkload(ctx context.Context, ID string) (io.Reader, io.Reader, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for AttachWorkload")
	}

	var r0 io.Reader
	var r1 io.Reader
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.Reader, io.Reader, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.Reader); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) io.Reader); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, ID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Runtime_AttachWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachWorkload'
type Runtime_AttachWorkload_Call struct {
	*mock.Call
}

// AttachWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *Runtime_Expecter) AttachWorkload(ctx any, ID any) *Runtime_AttachWorkload_Call {
	return &Runtime_AttachWorkload_Call{Call: _e.mock.On("AttachWorkload", ctx, ID)}
}

func (_c *Runtime_AttachWorkload_Call) Run(run func(ctx context.Context, ID string)) *Runtime_AttachWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_AttachWorkload_Call) Return(reader io.Reader, reader1 io.Reader, err error) *Runtime_AttachWorkload_Call {
	_c.Call.Return(reader, reader1, err)
	return _c
}

func (_c *Runtime_AttachWorkload_Call) RunAndReturn(run func(ctx context.Context, ID string) (io.Reader, io.Reader, error)) *Runtime_AttachWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// CollectWorkloadMetrics provides a mock function for the type Runtime
func (_mock *Runtime) CollectWorkloadMetrics(ctx context.Context, ID string) {
	_mock.Called(ctx, ID)
	return
}

// Runtime_CollectWorkloadMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectWorkloadMetrics'
type Runtime_CollectWorkloadMetrics_Call struct {
	*mock.Call
}

// CollectWorkloadMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *Runtime_Expecter) CollectWorkloadMetrics(ctx any, ID any) *Runtime_CollectWorkloadMetrics_Call {
	return &Runtime_CollectWorkloadMetrics_Call{Call: _e.mock.On("CollectWorkloadMetrics", ctx, ID)}
}

func (_c *Runtime_CollectWorkloadMetrics_Call) Run(run func(ctx context.Context, ID string)) *Runtime_CollectWorkloadMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_CollectWorkloadMetrics_Call) Return() *Runtime_CollectWorkloadMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *Runtime_CollectWorkloadMetrics_Call) RunAndReturn(run func(ctx context.Context, ID string)) *Runtime_CollectWorkloadMetrics_Call {
	_c.Run(run)
	return _c
}

// Events provides a mock function for the type Runtime
func (_mock *Runtime) Events(ctx context.Context, filters map[string]string) (<-chan *types.WorkloadEventMessage, <-chan error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan *types.WorkloadEventMessage
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) (<-chan *types.WorkloadEventMessage, <-chan error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) <-chan *types.WorkloadEventMessage); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *types.WorkloadEventMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) <-chan error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// Runtime_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type Runtime_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]string
func (_e *Runtime_Expecter) Events(ctx any, filters any) *Runtime_Events_Call {
	return &Runtime_Events_Call{Call: _e.mock.On("Events", ctx, filters)}
}

func (_c *Runtime_Events_Call) Run(run func(ctx context.Context, filters map[string]string)) *Runtime_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_Events_Call) Return(workloadEventMessageCh <-chan *types.WorkloadEventMessage, errCh <-chan error) *Runtime_Events_Call {
	_c.Call.Return(workloadEventMessageCh, errCh)
	return _c
}

func (_c *Runtime_Events_Call) RunAndReturn(run func(ctx context.Context, filters map[string]string) (<-chan *types.WorkloadEventMessage, <-chan error)) *Runtime_Events_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type Runtime
func (_mock *Runtime) GetStatus(ctx context.Context, ID string, checkHealth bool) (*types.WorkloadStatus, error) {
	ret := _mock.Called(ctx, ID, checkHealth)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *types.WorkloadStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*types.WorkloadStatus, error)); ok {
		return returnFunc(ctx, ID, checkHealth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *types.WorkloadStatus); ok {
		r0 = returnFunc(ctx, ID, checkHealth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.WorkloadStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, ID, checkHealth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runtime_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type Runtime_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
//   - checkHealth bool
func (_e *Runtime_Expecter) GetStatus(ctx any, ID any, checkHealth any) *Runtime_GetStatus_Call {
	return &Runtime_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, ID, checkHealth)}
}

func (_c *Runtime_GetStatus_Call) Run(run func(ctx context.Context, ID string, checkHealth bool)) *Runtime_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Runtime_GetStatus_Call) Return(workloadStatus *types.WorkloadStatus, err error) *Runtime_GetStatus_Call {
	_c.Call.Return(workloadStatus, err)
	return _c
}

func (_c *Runtime_GetStatus_Call) RunAndReturn(run func(ctx context.Context, ID string, checkHealth bool) (*types.WorkloadStatus, error)) *Runtime_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkloadName provides a mock function for the type Runtime
func (_mock *Runtime) GetWorkloadName(ctx context.Context, ID string) (string, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkloadName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runtime_GetWorkloadName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkloadName'
type Runtime_GetWorkloadName_Call struct {
	*mock.Call
}

// GetWorkloadName is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *Runtime_Expecter) GetWorkloadName(ctx any, ID any) *Runtime_GetWorkloadName_Call {
	return &Runtime_GetWorkloadName_Call{Call: _e.mock.On("GetWorkloadName", ctx, ID)}
}

func (_c *Runtime_GetWorkloadName_Call) Run(run func(ctx context.Context, ID string)) *Runtime_GetWorkloadName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_GetWorkloadName_Call) Return(s string, err error) *Runtime_GetWorkloadName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Runtime_GetWorkloadName_Call) RunAndReturn(run func(ctx context.Context, ID string) (string, error)) *Runtime_GetWorkloadName_Call {
	_c.Call.Return(run)
	return _c
}

// IsDaemonRunning provides a mock function for the type Runtime
func (_mock *Runtime) IsDaemonRunning(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsDaemonRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Runtime_IsDaemonRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDaemonRunning'
type Runtime_IsDaemonRunning_Call struct {
	*mock.Call
}

// IsDaemonRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runtime_Expecter) IsDaemonRunning(ctx any) *Runtime_IsDaemonRunning_Call {
	return &Runtime_IsDaemonRunning_Call{Call: _e.mock.On("IsDaemonRunning", ctx)}
}

func (_c *Runtime_IsDaemonRunning_Call) Run(run func(ctx context.Context)) *Runtime_IsDaemonRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runtime_IsDaemonRunning_Call) Return(b bool) *Runtime_IsDaemonRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Runtime_IsDaemonRunning_Call) RunAndReturn(run func(ctx context.Context) bool) *Runtime_IsDaemonRunning_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkloadIDs provides a mock function for the type Runtime
func (_mock *Runtime) ListWorkloadIDs(ctx context.Context, filters map[string]string) ([]string, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkloadIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) ([]string, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) []string); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runtime_ListWorkloadIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkloadIDs'
type Runtime_ListWorkloadIDs_Call struct {
	*mock.Call
}

// ListWorkloadIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]string
func (_e *Runtime_Expecter) ListWorkloadIDs(ctx any, filters any) *Runtime_ListWorkloadIDs_Call {
	return &Runtime_ListWorkloadIDs_Call{Call: _e.mock.On("ListWorkloadIDs", ctx, filters)}
}

func (_c *Runtime_ListWorkloadIDs_Call) Run(run func(ctx context.Context, filters map[string]string)) *Runtime_ListWorkloadIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_ListWorkloadIDs_Call) Return(strings []string, err error) *Runtime_ListWorkloadIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Runtime_ListWorkloadIDs_Call) RunAndReturn(run func(ctx context.Context, filters map[string]string) ([]string, error)) *Runtime_ListWorkloadIDs_Call {
	_c.Call.Return(run)
	return _c
}

// LogFieldsExtra provides a mock function for the type Runtime
func (_mock *Runtime) LogFieldsExtra(ctx context.Context, ID string) (map[string]string, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for LogFieldsExtra")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runtime_LogFieldsExtra_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogFieldsExtra'
type Runtime_LogFieldsExtra_Call struct {
	*mock.Call
}

// LogFieldsExtra is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *Runtime_Expecter) LogFieldsExtra(ctx any, ID any) *Runtime_LogFieldsExtra_Call {
	return &Runtime_LogFieldsExtra_Call{Call: _e.mock.On("LogFieldsExtra", ctx, ID)}
}

func (_c *Runtime_LogFieldsExtra_Call) Run(run func(ctx context.Context, ID string)) *Runtime_LogFieldsExtra_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runtime_LogFieldsExtra_Call) Return(stringToString map[string]string, err error) *Runtime_LogFieldsExtra_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Runtime_LogFieldsExtra_Call) RunAndReturn(run func(ctx context.Context, ID string) (map[string]string, error)) *Runtime_LogFieldsExtra_Call {
	_c.Call.Return(run)
	return _c
}
